name: CrystalCavernsBasic
author: 'japicraft'
version: '1.0'
main: cc.crystalcavernsbasic.CrystalCavernsBasic
api-version: '1.20'
commands:
  spawn:
    description: Teleport the player to the server's global spawn point.
    aliases: [lobby, hub]