name: CrystalCavernsBasic
version: '1.0'
main: cc.crystalcavernsbasic.CrystalCavernsBasic
api-version: 1.19
depend: [CommandPanels]
commands:
  profile:
    description: Used to open a player's profile.